name: update-assets

on:
  workflow_dispatch:
  schedule:
    - cron: 00 09 * * *

jobs:
  updateassets:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'

    - name: Pull build ref file from dbatools
      working-directory: assets
      run: curl -O https://raw.githubusercontent.com/dataplat/dbatools/development/bin/dbatools-buildref-index.json

    - name: Pull index file from dbatools
      working-directory: assets
      run: curl -O https://raw.githubusercontent.com/dataplat/dbatools/development/bin/dbatools-index.json

    - name: commit if file changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: updating build ref file

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
